### ISSUE TITLE
Standardize data.

### ISSUE THREAD

**Issue by mrcbax** [BuzzFeedNews/zika-data#10]
Surprise! Applications lake KNIME and ArcGIS have no clue what a `tab separated value file` is. I would suggest converting it to CSV.

[paho-who-cases-reported-2016-02-24.tsv](https://raw.githubusercontent.com/BuzzFeedNews/zika-data/master/data/raw/paho-who/paho-who-cases-reported-2016-02-24.tsv)

This can easily be done by renaming the file extension to `.csv` and using a find and replace tool in your favorite editor to replace `\t` with `,`

**Comment by jsvine** [comment]
Hi, Chad, and thanks for the note! As you've probably noticed, that file is in the `data/raw` folder. As such, it's preserved in exactly the format we found it. But I believe that all other processed, tabular files are presented as CSVs.
